#!/usr/bin/env bash
# Generate registry.yaml from the skills' frontmatter — the published index that
# downstream consumers check for updates (new skills, version bumps, deprecations).
# Run after changing any skill's version/requires/deprecated frontmatter, and commit
# the result. CI can assert it's up to date (build-registry then `git diff --exit-code`).
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
out="registry.yaml"

fm_field() {  # fm_field <frontmatter-text> <key>
  printf '%s\n' "$1" | sed -n "s/^$2:[[:space:]]*//p" | head -1
}

{
  echo "# Auto-generated by scripts/build-registry.sh — do not edit by hand."
  echo "# Published index of skills: per-skill version, content hash, dependencies, deprecation."
  echo "# Downstream consumers compare their .agents/skills-lock.json against this to find updates."
  echo "schema: 1"
  echo "skills:"
  for d in skills/*/; do
    name="$(basename "$d")"
    f="${d}SKILL.md"
    [ -f "$f" ] || continue
    fm="$(awk 'NR==1&&/^---/{f=1;next} f&&/^---/{exit} f{print}' "$f")"
    ver="$(fm_field "$fm" version)"
    req="$(fm_field "$fm" requires)"
    dep="$(fm_field "$fm" deprecated)"
    sha="$(sha256sum "$f" | cut -d' ' -f1)"
    echo "  ${name}:"
    echo "    version: ${ver:-0.0.0}"
    echo "    sha256: ${sha}"
    [ -n "$req" ] && echo "    requires: ${req}"
    [ -n "$dep" ] && echo "    deprecated: ${dep}"
  done
} > "$out"

echo "Wrote $out ($(grep -c '^  [a-z]' "$out") skills)"
