#!/usr/bin/env bash
# Generate registry.yaml from the skills' frontmatter — the published index that
# downstream consumers check for updates (new skills, version bumps, deprecations).
# Also verifies every skills/*/ directory is listed in README.md's "What's here" tree,
# so a new skill can't silently go undocumented there.
# Run after changing any skill, and commit the result. CI can assert it's up to date
# (build-registry then `git diff --exit-code`).
set -euo pipefail
# shellcheck source=scripts/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh" || { echo "build-registry: cannot source lib.sh" >&2; exit 3; }
shopt -s nullglob
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
# Pin collation so the `skills/*/` glob order (and thus registry.yaml ordering) is identical
# across machines/locales — otherwise a non-C dev regenerates a reordered file that CI's
# `git diff --exit-code` then flags as stale. (skill_dir_hash already pins LC_ALL=C internally.)
export LC_ALL=C
out="registry.yaml"

fm_field()  { printf '%s\n' "$1" | sed -n "s/^$2:[[:space:]]*//p" | head -1; }
fm_scalar() { fm_field "$1" "$2" | sed 's/[[:space:]]*#.*$//; s/[[:space:]]*$//'; }
yesc()      { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }   # escape for a YAML double-quoted scalar
# skill_dir_hash() comes from lib.sh — the single source of truth.

{
  echo "# Auto-generated by scripts/build-registry.sh — do not edit by hand."
  echo "# Published index of skills: per-skill version, whole-dir content hash, deps, access, deprecation."
  echo "# Downstream consumers compare their .agents/skills-lock.json against this to find updates."
  echo "schema: 1"
  echo "skills:"
  for d in skills/*/; do
    name="$(basename "$d")"
    f="${d}SKILL.md"
    [ -f "$f" ] || continue
    fm="$(awk 'NR==1&&/^---/{f=1;next} f&&/^---/{exit} f{print}' "$f")"
    ver="$(fm_scalar "$fm" version)"
    req="$(fm_scalar "$fm" requires)"
    acc="$(fm_scalar "$fm" default-access)"
    iso="$(fm_scalar "$fm" isolation)"
    dep="$(fm_scalar "$fm" deprecated)"
    sha="$(skill_dir_hash "$d")"
    echo "  ${name}:"
    echo "    version: ${ver:-0.0.0}"
    echo "    sha256: ${sha}"
    [ -n "$req" ] && echo "    requires: ${req}"
    [ -n "$acc" ] && echo "    default-access: \"$(yesc "$acc")\""
    [ -n "$iso" ] && echo "    isolation: ${iso}"
    [ -n "$dep" ] && echo "    deprecated: \"$(yesc "$dep")\""
  done
} > "$out"

echo "Wrote $out ($(grep -c '^  [a-z]' "$out") skills)"

# README.md's "What's here" tree is hand-curated prose (cross-references, nested files like
# subagent-framework/reference.md) — not worth regenerating and flattening. Instead, catch the
# exact drift that motivated this check: a skill added here but never mentioned there. Fixture
# "hubs" (e.g. scripts/test/*.test.sh) build a registry with no README.md at all — skip there,
# only enforce when this is a real checkout of the hub.
if [ -f README.md ]; then
  missing=()
  for d in skills/*/; do
    name="$(basename "$d")"
    [ -f "${d}SKILL.md" ] || continue
    grep -qE "^  ${name}/" README.md || missing+=("$name")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    echo "::error::README.md's \"What's here\" tree is missing: ${missing[*]}" >&2
    echo "Add a line for each under '## What's here' in README.md, then re-run." >&2
    exit 1
  fi
fi
